### PR TITLE
Fixes type conversion warning in Xcode 6.3 beta

### PR DESCRIPTION
**Pull request by shagedorn**

### CODE REVIEW

**Comment by RyanCopley** [comment]
@danielamitay I know this is conflicted, but can you please do this? This is the only warning in my project :(

**Comment by RyanCopley** [comment]
Actually, looking closer, this WAS fixed. Could you please just create a new tag, @danielamitay ?

**Comment by danielamitay** [comment]
Fixed by #47 and new tag 2.3.0 created

**Comment by RyanCopley** [comment]
:+1:

**Pull request closed without merging**
